---

- name: "Generate systemd Odoo service: {{ odoo_service }}"
  template:
        src=odoo.service
        dest=/etc/systemd/system/{{ odoo_service }}.service
        owner=root group=root mode=0555
        force=yes
        backup=no

#- name: "Generate systemd Odoo cronworker service: {{ odoo_service }}"
#  template:
#        src=odoo-cron.service
#        dest=/etc/systemd/system/{{ odoo_service }}_cronworker.service
#        owner=root group=root mode=0555
#        force=yes
#        backup=no

- name: "Reload Systemd: {{ odoo_service }}"
  systemd:
    daemon-reload: yes
  when: ansible_service_mgr == 'systemd'

- name: "Restart Odoo: {{ odoo_service }}"
  service:
    name: "{{ odoo_service }}"
    state: restarted
  tags:
    - install

#- name: "Restart Odoo: {{ odoo_service }}_cronworker"
#  service:
#    name: "{{ odoo_service }}_cronworker"
#    state: restarted
#  tags:
#    - instance
#    - install
#  # TODO: reduce restarts when not needed

- name: "Enable Odoo service: {{ odoo_service }}"
  service: name={{ odoo_service }} enabled=yes state=started

#- name: "Enable Odoo service: {{ odoo_service }}_cronworker"
#  service: name="{{ odoo_service }}_cronworker" enabled=yes state=started
#  tags: instance
