---

- name: Set variables depending on the platform and the version of Odoo
  include_vars:
    file: "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}_Odoo-{{ odoo_version | int }}.yml"
  tags:
    - install
    - addons
    - instance

- import_tasks: install.yml
  tags: install

- import_tasks: wkhtmltox.yml
  tags: install

- import_role:
    name: derico.odoo_addons
  vars:
    odoo_addon_repos: "{{ odoo_setup.odoo_addon_repos }}"
    odoo_version: "{{ odoo_setup.version }}"
    odoo_user: "{{ odoo_setup.odoo_user }}"
  when: "'odoo_addon_repos' in odoo_setup"
  tags: addons

- name: "Run instance tasks for every instance in version {{ odoo_version }}"
  include_tasks: instance.yml
  loop: "{{ odoo_setup.instances }}"
  loop_control:
    loop_var: odoo_instance
  tags: instance
