---

- name: Set variables depending on the platform and the version of Odoo
  include_vars:
    file: "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}_Odoo-{{ odoo_version | int }}.yml"

- import_tasks: install.yml

- name: "Run instance tasks for every instance in version {{ odoo_version }}"
  include_tasks: instance.yml
  loop: "{{ odoo_setup.instances }}"
  loop_control:
    loop_var: odoo_instance
